"""This file contains the default values of parameters used in respect"""


VALID_FILE_EXTENSIONS = ['.fq', '.fastq', '.fa', '.fna', '.fasta', '.hist']
ASSEMBLY_CONTIG_LENGTH_THRESHOLD = 2000

HIGHEST_JELLYFISH_HISTO_MULTIPLICITY = 10 ** 8
SPECTRA_OUTPUT_SIZE = 5

HCRM_NUMBER = 10
MAX_COVERAGE = 100

KMER_SIZE = 31
ITERATIONS = 1000
TEMPERATURE_COEFFICIENT = 1.0
CONTRACTION_COEFFICIENT = 1.0
MINIMUM_R1L = 0.1
ERROR_FUNCTION_NORM = 1
SPECTRA_NUMBER = 50
RANDOM_NEIGHBOUR_SEED = 1491852112
ACCEPTANCE_SEED = 1491852212

SPLINE_NUMBER = 5
ERROR_CORRECTION_COVERAGE_THRESHOLD = 1.5
